name: PR Gate
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.6.3
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - run: pnpm install
      - name: Lint mdx package
        run: pnpm --filter @_janina/mdx lint
      - name: Lint ui package
        run: pnpm --filter @_janina/ui lint
      - name: Build mdx package
        run: pnpm --filter @_janina/mdx build
      - name: Test build ui package
        run: pnpm --filter @_janina/ui build
      - name: Re-install to consume newly build mdx package
        run: pnpm install
      - name: Lint docs package
        run: pnpm --filter @_janina/docs lint
      - name: Build docs package
        run: pnpm --filter @_janina/docs build
