name: PR Gate
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.32.2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
      - run: pnpm install
      - name: Lint mdx package
        run: pnpm --filter @jannnik/mdx lint
      - name: Lint ui package
        run: pnpm --filter @jannnik/ui lint
      - name: Build mdx package
        run: pnpm --filter @jannnik/mdx build
      - name: Re-install to consume newly build mdx package
        run: pnpm install
      - name: Lint docs package
        run: pnpm --filter @jannnik/docs lint
      - name: Build docs package
        run: pnpm --filter @jannnik/docs build
